version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8876:80
    depends_on:
      - app
    container_name: test-task_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: test-task_app
    depends_on:
      - db

  db:
    image: postgres:14.5
    restart: always
    environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: postgres
    ports:
      - 5432:5432
    container_name: task_db
